
backend = "glx";
vsync = true;

wintypes:
{
  dock = {
    round-corners = false;
    clip-shadow-above = true;
    shadow = false;
  };
};

rounded-corners-exclude = [
  "class_g = 'Dunst'",
  "class_g = 'Polybar'",
  "class_g = 'Rofi'"
];

# Visual
corner-radius = 15;
shadow = true;
shadow-radius = 5;
shadow-opacity = 0.70;
shadow-offset-x = 1;
shadow-offset-y = 1;


# Animações
@include "picom_animations.conf"
