#!/usr/bin/sh

# Iniciando os scripts
~/.config/bspwm/autostart.sh &

bspc monitor -d I II III

bspc config pointer_action1 move 
bspc config pointer_action2 resize_side 
bspc config pointer_action2 resize_corner 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config automatic_scheme spiral
bspc config initial_polarity first_child

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color2"
bspc config presel_feedback_color "$color1"
bspc config focus_follows_pointer true

bspc rule -a ncmpcpp state=floating center=on rectangle=80x24+center
bspc rule -a fastfetch state=floating center=on
