#!/usr/bin/sh

# Wallpaper
~/dotfiles/feh/wallchange-startup.sh

# Cores do pywal
source "$HOME/.cache/wal/colors.sh"

# Dunst
killall dunst
dunst &

# PywalFox
pywalfox update

# Polybar
bash ~/.config/polybar/launch.sh --shades

# Teclas
sxhkd &

# Picom
picom &

# BetterLockScreen
betterlockscreen -u "$WALLPAPER" --fx blur

# Inicia o MPD
pgrep -x mpd > /dev/null || mpd --no-daemon &

# Inicia o mpdscribble
pgrep -x mpdscribble > /dev/null || mpdscribble &

# Cursor
xsetroot -cursor_name left_ptr &

bspc monitor -d I II III

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config automatic_scheme spiral
bspc config initial_polarity first_child

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color2"
bspc config presel_feedback_color "$color1"
bspc config focus_follows_pointer true

bspc rule -a ncmpcpp state=floating center=on rectangle=80x24+center

