# Shell variables
# Generated by 'wal'
wallpaper='/home/julliermy/wallpapers/137.jpg'

# Special
background='#0d0807'
foreground='#c19c9f'
cursor='#c19c9f'

# Colors
color0='#0d0807'
color1='#9C1519'
color2='#91282E'
color3='#B0262C'
color4='#F41A1B'
color5='#F41D22'
color6='#D22024'
color7='#c19c9f'
color8='#876d6f'
color9='#9C1519'
color10='#91282E'
color11='#B0262C'
color12='#F41A1B'
color13='#F41D22'
color14='#D22024'
color15='#c19c9f'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
