--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/julliermy/wallpapers/176.jpg"

-- Special
background="#0e1012"
foreground="#eee9d5"
cursor="#eee9d5"

-- Colors
color0="#0e1012"
color1="#A1927E"
color2="#B6A98F"
color3="#C7B99A"
color4="#D0C19F"
color5="#D4C4A2"
color6="#E3D3AE"
color7="#eee9d5"
color8="#a6a395"
color9="#A1927E"
color10="#B6A98F"
color11="#C7B99A"
color12="#D0C19F"
color13="#D4C4A2"
color14="#E3D3AE"
color15="#eee9d5"
