--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/julliermy/wallpapers/137.jpg"

-- Special
background="#0d0807"
foreground="#c19c9f"
cursor="#c19c9f"

-- Colors
color0="#0d0807"
color1="#9C1519"
color2="#91282E"
color3="#B0262C"
color4="#F41A1B"
color5="#F41D22"
color6="#D22024"
color7="#c19c9f"
color8="#876d6f"
color9="#9C1519"
color10="#91282E"
color11="#B0262C"
color12="#F41A1B"
color13="#F41D22"
color14="#D22024"
color15="#c19c9f"
