# Shell variables
# Generated by 'wal'
wallpaper='/home/julliermy/wallpapers/176.jpg'

# Special
background='#0e1012'
foreground='#eee9d5'
cursor='#eee9d5'

# Colors
color0='#0e1012'
color1='#A1927E'
color2='#B6A98F'
color3='#C7B99A'
color4='#D0C19F'
color5='#D4C4A2'
color6='#E3D3AE'
color7='#eee9d5'
color8='#a6a395'
color9='#A1927E'
color10='#B6A98F'
color11='#C7B99A'
color12='#D0C19F'
color13='#D4C4A2'
color14='#E3D3AE'
color15='#eee9d5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
